### ISSUE TITLE
Error Invalid image

### ISSUE THREAD

**Issue by emma-dev** [Dmitry-Borodin/pdfview-android#30]
hi ,using pdf viewer-android library and an error like this came out « exifinterface got an unsupported image format file(exifinterface supports jpeg and some raw image formats only) or a corrupted jpeg file to exifinterface.», how can I solve it?  Thank you

**Comment by Dmitry-Borodin** [comment]
I don't know. Is that always reproducible? Can you provide full stacktrace?

**Comment by emma-dev** [comment]
Hello, Do you speak Russian?

Чт 13.5.2021 в 01:33, Dmitry Borodin ***@***.***>:

**Comment by emma-dev** [comment]
Hello, Do you speak Russian?

**Comment by emma-dev** [comment]
W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
    java.io.IOException: Invalid byte order: 2550
        at android.media.ExifInterface.readByteOrder(ExifInterface.java:3121)
        at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2437)
        at android.media.ExifInterface.getMimeType(ExifInterface.java:2315)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1753)
        at android.media.ExifInterface.initForFilename(ExifInterface.java:2297)
        at android.media.ExifInterface.<init>(ExifInterface.java:1384)
        at com.example.kireinewk.muut.SubsamplingScaleImageView.getExifOrientation(SubsamplingScaleImageView.java:1872)
        at com.example.kireinewk.muut.SubsamplingScaleImageView.access$5200(SubsamplingScaleImageView.java:77)
        at com.example.kireinewk.muut.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1574)
        at com.example.kireinewk.muut.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1546)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by emma-dev** [comment]
I rewrote your code in Java

**Comment by emma-dev** [comment]
In Activity I wrote only this line of code pinView.fromAsset(this,"Osa C.pdf").show();

**Comment by Dmitry-Borodin** [comment]
Line numbers are different, could you run it on a sample project of this library (just change pdf file for sample).
This will help to see if you broke something while rewriting as well.

But most probably this is broken pdf file... Other readers may restore from this situation, since content can be shown without this data.

**Comment by emma-dev** [comment]
I wrote line of code pinView.fromAsset(this,"paper.pdf").show();

and got this error

E/SubsamplingScaleImageView: Failed to initialise bitmap decoder
    java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:315)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:220)
        at com.example.kireinewk.lib.PDFRegionDecoder.init(PDFRegionDecoder.java:116)
        at com.example.kireinewk.muut.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1571)
        at com.example.kireinewk.muut.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1546)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by emma-dev** [comment]
Okay, try to run sample project

**Comment by emma-dev** [comment]
Can you help me, rewrite in Java this

getExternalFilesDir(null)?.mkdirs() // create a folder for the first run
        val pdfs: Array<File> = getExternalFilesDir(null)?.listFiles { _: File?, name: String -> name.endsWith(".pdf") }
                ?: emptyArray()

        val list = mutableListOf<String>()
        pdfs.forEach { list.add(it.name) }

        if (list.size > 0) {
            AlertDialog.Builder(this)
                    .setTitle("List of files")
                    .setItems(list.toTypedArray()) { _: DialogInterface?, item: Int ->
                        view.fromFile(File(getExternalFilesDir(null), list[item]))
                        view.show()
                    }
                    .show()
        } else {
            view.fromAsset("great-expectations.pdf")
            view.show()
        }

**Comment by Dmitry-Borodin** [comment]
This stacktrace is not from the project you opened issue on. Please open this file from this project sample.
You will immediately see if you broke something when migrating to java or if it's problem of pdf file.

**Comment by emma-dev** [comment]
I am sorry, I am just a beginner, and I dont quite understand what sample project you are talking about, and how can I do it?

Thanks
