### ISSUE TITLE
Crashes while opening large pdf

### ISSUE THREAD

**Issue by SaurabhDhage** [Dmitry-Borodin/pdfview-android#41]
It work like charm when opening small pdfs but crashes when I try to open pdf with 2000 pages.

**Comment by developerdaya** [comment]
Facing Same Issue, App Crash While opening the 900 Page PDF
If there Is  any Solution, would be appreciated 
FATAL EXCEPTION: main (Ask Gemini)
java.lang.IllegalArgumentException: Illegal Capacity: -6
	at java.util.ArrayList.<init>(ArrayList.java:170)
	at com.pdfview.subsamplincscaleimageview.SubsamplingScaleImageView.initialiseTileMap(SubsamplingScaleImageView.java:1510)
	at com.pdfview.subsamplincscaleimageview.SubsamplingScaleImageView.initialiseBaseLayer(SubsamplingScaleImageView.java:1276)
	at com.pdfview.subsamplincscaleimageview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.java:985)
	at android.view.View.draw(View.java:21635)
	at android.view.View.updateDisplayListIfDirty(View.java:20476)
	at android.view.View.draw(View.java:21351)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4485)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4237)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.updateDisplayListIfDirty(View.java:20467)
	at android.view.View.draw(View.java:21351)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4485)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4237)
	at android.view.View.updateDisplayListIfDirty(View.java:20467)
	at android.view.View.draw(View.java:21351)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4485)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4237)
	at android.view.View.updateDisplayListIfDirty(View.java:20467)
	at android.view.View.draw(View.java:21351)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4485)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4237)
	at android.view.View.updateDisplayListIfDirty(View.java:20467)
	at android.view.View.draw(View.java:21351)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4485)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4237)
	at android.view.View.updateDisplayListIfDirty(View.java:20467)
	at android.view.View.draw(View.java:21351)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4485)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4237)
	at android.view.View.draw(View.java:21642)
	at com.android.internal.policy.DecorView.draw(DecorView.java:842)
	at android.view.View.updateDisplayListIfDirty(View.java:20476)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3874)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3660)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2980)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1882)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8047)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:860)
	at android.view.Choreographer.doFrame(Choreographer.java:785)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
