### ISSUE TITLE
File is not in PDF Format

### ISSUE THREAD

**Issue by azhan3211** [Dmitry-Borodin/pdfview-android#45]
Log tells that my PDF file is not PDF format when i build it on release
but it work fine on debug

```
java.io.IOException: file not in PDF format or corrupted
        at android.graphics.pdf.PdfRenderer.nativeCreate(Native Method)
        at android.graphics.pdf.PdfRenderer.<init>(PdfRenderer.java:171)
        at com.myapp.d.a(SourceFile:31)
        at com.pdfview.subsamplincscaleimageview.SubsamplingScaleImageView$l.a(SourceFile:1658)
        at com.pdfview.subsamplincscaleimageview.SubsamplingScaleImageView$l.doInBackground(SourceFile:1633)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by yess-wee** [comment]
I think you have to add permission for the files which are located in external storage.

Add READ_EXTERNAL_STORAGE permission in app's manifest file.
