### ISSUE TITLE
Failure to load files smaller than about 4k

### ISSUE THREAD

**Issue by KennyGoers** [Dmitry-Borodin/pdfview-android#53]
I have a problem loading files smaller than 4K, always get the following exception:

```
 E/SubsamplingScaleImageView: Failed to load bitmap
    java.lang.RuntimeException: Skia image region decoder returned null bitmap - image format may not be supported
        at com.pdfview.subsamplincscaleimageview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:102)
        at com.pdfview.subsamplincscaleimageview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1748)
        at com.pdfview.subsamplincscaleimageview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1722)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

Anyone see a similar issue? Continuing to hunt down, but wondering if anyone else is seeing it

**Comment by Dmitry-Borodin** [comment]
I'm not aware of this one.

**Comment by KennyGoers** [comment]
I can add a couple example files, but couldn't find a way to attach them.

**Comment by KennyGoers** [comment]
I've included a couple PDF files that cause this scenario. 

I also noticed you use SubsamplingScaleImageView which is a separate project but include the files directly, did you have to modify them? Is this possible something that was a bug in SubsamplingScaleImageView but is fixed in a newer version than you used

[preview4876264608160207447.pdf](https://github.com/Dmitry-Borodin/pdfview-android/files/9006800/preview4876264608160207447.pdf)
[preview3882795994610281957.pdf](https://github.com/Dmitry-Borodin/pdfview-android/files/9006802/preview3882795994610281957.pdf)

**Comment by bhavik45** [comment]
Facing the same issue only on android 13, Does anyone have any idea? 

Working fine for android 12 and lower.

I think it is not a file size issue. It is android 13.

**Comment by DeveloperIbv** [comment]
Hello

As bhavik45 said:
Is there a general problem running in Android-13 ?

Can someone confirm this?

Kind regards.
